// messages.js: 메시지 타입 정의
export const MESSAGE_TYPES = {
  OPEN_SIDEPANEL: "OPEN_SIDEPANEL",
  SUMMARIZE_PAGE: "SUMMARIZE_PAGE",
  EXTRACT_IMG: "EXTRACT_IMG",
  EXTRACT_TEXT: "EXTRACT_TEXT",
  UPDATE_SIDEPANEL: "UPDATE_SIDEPANEL"
};
